## 00. PyTorch Fundamentals

In [ ]:
import torch
print(torch.__version__)

2.11.0+cpu


# Introduction to Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(MATRIX, MATRIX.ndim)

tensor([[ 7,  8],
        [ 9, 10]]) 2


In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.5794, 0.0768, 0.4205, 0.2292],
         [0.2025, 0.8755, 0.0338, 0.5272],
         [0.7114, 0.1383, 0.3042, 0.2564]],

        [[0.6108, 0.4877, 0.7161, 0.9541],
         [0.6364, 0.3830, 0.4538, 0.0970],
         [0.9545, 0.2068, 0.2346, 0.2728]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels(r,b,g)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [ ]:
#Create a tensor of all zeros

zero = torch.zeros(3,4)
ones = torch.ones(3,4)
zero, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [ ]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [ ]:
#Use torch.range()
one_to_1k = torch.arange(0,1000,67)
one_to_1k

tensor([  0,  67, 134, 201, 268, 335, 402, 469, 536, 603, 670, 737, 804, 871,
        938])

In [ ]:
#Creating tnesors like
ten_zeros = torch.zeros_like(one_to_1k)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [ ]:
#  Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (eg float32 and float16)
                               device = None, #What device is your tensor on (eg cpu or cuda)
                               requires_grad = False, #Whether or not to track the gradients
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

Manipulating tensor Operations

In [ ]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor_T =  torch.rand([3,4])
tensor_T

tensor([[0.0429, 0.2752, 0.6941, 0.5070],
        [0.0782, 0.6592, 0.2184, 0.4134],
        [0.4334, 0.8082, 0.7320, 0.4697]])

In [ ]:
tensor_T.T

tensor([[0.0429, 0.0782, 0.4334],
        [0.2752, 0.6592, 0.8082],
        [0.6941, 0.2184, 0.7320],
        [0.5070, 0.4134, 0.4697]])

##Finding the min, max, mean, sum ,etc (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#The torch.mean function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

##Finding the positional min and max

In [ ]:
#FInd the position in tensor that has the minimum value with argmin() and vice versa for argmax()
x.argmin()

tensor(0)

##Reshaping, stacking, squeezing and unsqueezing

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x because the view of tensor shares the same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top
x_stacked = torch.stack([x_reshaped,x_reshaped,x_reshaped,x_reshaped], dim = 0)
x_stacked

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
# torch.squeeze() -  removes all single dimensions from a target tensor
x_reshaped, x_reshaped.squeeze()
x_squeezed = x_reshaped.squeeze()

In [ ]:
x_reshaped.shape, x_reshaped.squeeze().shape, x.shape

(torch.Size([1, 9]), torch.Size([9]), torch.Size([9]))

In [ ]:
# torch.unsqueeze() - adds a single dmension to a tagret tensor at a specific dim (dimension)

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 244, 3)) # [height, width, color_channels]

#Permute the originak tensor to reaarange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colors_channels, height, widht]

Previous shape: torch.Size([224, 244, 3])
New shape: torch.Size([3, 224, 244])


In [ ]:
x_original[0,0,0] = 2345.
x_permuted[0,0,0] #Shallow copy of original

tensor(2345.)

##Indexing (selecting data from tensors)

Indexing with Pytroch is similar to indexing with Numpy.

In [ ]:
#Create a tensor
import torch

x = torch.arange(1, 13).reshape(2, 2, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]]),
 torch.Size([2, 2, 3]))

In [ ]:
#Let's indexo on our new tensor
x[:,0,:]

tensor([[1, 2, 3],
        [7, 8, 9]])

In [ ]:
#Let's index on the middle bracket (dim=1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
#Lets index on the most inner bracket(last dimension)
x[1,0,0]


tensor(7)

##PyTorch tensors & NumPy

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.tensor.numpy()

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array).type(torch.float32) #when converting from numpy to pytorch, it reflects the default datatype of numpy array
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
#changing the value of array and ovserving tensor
array = array + 1
array ,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
#Changing tensor and observing numpy_tensor
tensor = tensor + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

##Reproducibility (trying to take the random out of random)

In short how a nueral network learns is:

'Starrt with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again

To reduce the randomness in neural network we introduce concept of a random seed.


In [ ]:
import torch

# Create two random tensors
rand_a = torch.rand(3,4)
rand_b = torch.rand(3,4)
print(rand_a)
print(rand_b)
print(rand_a == rand_b)

tensor([[0.1584, 0.6574, 0.4644, 0.0752],
        [0.5904, 0.1902, 0.6140, 0.5907],
        [0.5154, 0.9400, 0.7861, 0.8930]])
tensor([[0.6645, 0.1881, 0.7742, 0.1074],
        [0.7631, 0.8430, 0.5133, 0.7066],
        [0.9181, 0.5272, 0.2265, 0.5563]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducable tensors

import torch

#Set the random seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
rand_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
rand_d = torch.rand(3,4)

print(rand_c)
print(rand_d)
print(rand_c == rand_d)


tensor([[0.5349, 0.1988, 0.6592, 0.6569],
        [0.2328, 0.4251, 0.2071, 0.6297],
        [0.3653, 0.8513, 0.8549, 0.5509]])
tensor([[0.5349, 0.1988, 0.6592, 0.6569],
        [0.2328, 0.4251, 0.2071, 0.6297],
        [0.3653, 0.8513, 0.8549, 0.5509]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

In [ ]:
!nvidia-smi

Thu Aug 20 13:06:44 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
#Check for GPU access with PyTorch

import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [ ]:
#Create a tensor
tensor = torch.tensor([1,2,3], device="cpu")

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Mvoe tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

##Moving tensors back to GPU

In [ ]:
#If tensor is no GPU can't transform it to NUmpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#To fix the GPU tensor with numpy issue, we can first set it to the CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')